POST  http://localhost:3000/dashboard
Content-Type: application/json

{
    "title": "chandal",
    # "image": "alt",
    "category": "Pantalones",
    "size": "XS",
    "price": "25"
    }

###

GET http://localhost:3000/products
Content-Type: application/json

###

put http://localhost:3000/change/65e4b7e47c9741682cfce8a5
Content-Type: application/json

{
    "title":"vaqueros"
}

###

DELETE  http://localhost:3000/dashboard/65ea126161e7d76ef6c32f77/delete
Content-Type: application/json


###

GET http://localhost:3000/product/65ecc47bc9510a7887e5c58d
Content-Type: application/json


